// Local dev runs on zero-setup SQLite while production (Vercel) runs on Postgres.
// Prisma can't pick the provider from an env var, so derive a SQLite copy of
// schema.prisma (gitignored), then generate the client and sync dev.db.
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';

const src = readFileSync('prisma/schema.prisma', 'utf8');
const local =
  '// GENERATED by scripts/prisma-local.mjs — edit schema.prisma instead.\n' +
  src
    .replace(/provider\s*=\s*"postgresql"/, 'provider = "sqlite"')
    .replace(/^\s*directUrl\s*=.*$/m, '')
    .replace(/^\s*binaryTargets\s*=.*$/m, '');
writeFileSync('prisma/schema.local.prisma', local);

const run = (cmd) => execSync(cmd, { stdio: 'inherit' });

// Skip generate when the client was already built from this exact schema: it's
// faster, and on Windows a running backend locks the engine DLL anyway.
const built = 'node_modules/.prisma/client/schema.prisma';
const squash = (s) => s.replace(/\s+/g, ''); // Prisma reformats its stored copy
const upToDate = existsSync(built) && squash(readFileSync(built, 'utf8')) === squash(local);
if (!upToDate) run('npx prisma generate --schema prisma/schema.local.prisma');
if (process.argv.includes('--push')) {
  run('npx prisma db push --skip-generate --schema prisma/schema.local.prisma');
}
